left_folder: "stereo_imgs/LabTest/Left/"
right_folder: "stereo_imgs/LabTest/Right/"
left_camera_config: "config/camera_cal/Left_Air.xml"
right_camera_config: "config/camera_cal/Right_Air.xml"
stereo_camera_config: "config/camera_cal/Stereo_Air.xml"
baseline: 120  # mm
BGR: True # Leave False for RGB or Greyscale // Will be assumed RGB if using live feed
Live: False # Live stereo feed?
use_stereo_config: True