left_folder: "CalibrationImgs/TestSet/Left/"
right_folder: "CalibrationImgs/TestSet/Right/"
left_camera_config: "config/camera_cal/Left_test.xml"
right_camera_config: "config/camera_cal/Right_test.xml"
baseline: 120  # mm
